name: build-release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]

env:
  ENABLE_GH_MAVEN: false

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.context.outputs.branch }}
      shouldBuild: ${{ steps.context.outputs.decision_build }}
      shouldPublish: ${{ steps.context.outputs.decision_publish }}
      isRelease: ${{ steps.context.outputs.isTag }}
      version: ${{ steps.context.outputs.version }}
      commitId: ${{ steps.context.outputs.shortCommitId }}
      semanticVersion: ${{ steps.conclusion.outputs.semanticVersion }}
      dockerTags: ${{ steps.conclusion.outputs.dockerTags }}
      dockerLabels: ${{ steps.docker_context.outputs.labels }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          git-push-gpgsign: false
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Project context
        id: context
        uses: zero88/gh-project-context@v1
        with:
          dry: false
          mustSign: true

      - name: Docker meta
        id: docker_context
        uses: crazy-max/ghaction-docker-meta@v1
        if: steps.context.outputs.decision_build == 'true'
        with:
          images: qwe-iot-gateway
          tag-latest: true
          tag-sha: true
          sep-tags: ","
          sep-labels: ","
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Conclusion
        if: steps.context.outputs.decision_build == 'true'
        id: conclusion
        shell: bash
        run: |
          [[ "${{ steps.context.outputs.isTag }}" == "true" ]] && sv="" || sv=$(grep semanticVersion gradle.properties | cut -d'=' -f2)
          dockerTags="${{ steps.docker_context.outputs.tags }}"
          echo "$dockerTags"
          echo "${{ steps.docker_context.outputs.labels }}"
          echo ::set-output name=semanticVersion::$sv
          echo ::set-output name=dockerTags::${dockerTags//qwe-iot-gateway:/}

  build:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    steps:
      - uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        if: needs.context.outputs.shouldPublish == 'true'
        with:
          git-user-signingkey: true
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: needs.context.outputs.shouldPublish == 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: needs.context.outputs.shouldPublish == 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: needs.context.outputs.shouldPublish == 'true'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: needs.context.outputs.shouldPublish == 'true'
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.OSS_GHA_DOCKER_HUB }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-build

      - name: Build
        run: |
          ./gradlew clean build -x test \
                          -Pversion=${{ needs.context.outputs.version }} \
                          -PsemanticVersion=${{needs.context.outputs.semanticVersion }} \
                          -PbuildBy="GitHub Action" -PbuildHash=${{ needs.context.outputs.commitId }}

      - name: Docker
        run: |
          ./gradlew pushDocker -x test \
                        -Pversion=${{ needs.context.outputs.version }} \
                        -PsemanticVersion=${{needs.context.outputs.semanticVersion }} \
                        -PdockerTags="${{ needs.context.outputs.dockerTags }}" \
                        -PdockerLabels="${{ needs.context.outputs.dockerLabels }}" \
                        -PdockerRegistries="ghcr.io/zero88,docker.io/zero88" \
                        -PbuildBy="GitHub Action" -PbuildHash=${{ needs.context.outputs.commitId }}

      - uses: actions/upload-artifact@v2
        with:
          name: iot
          path: ${{ github.workspace }}/build/distributions/*.zip
          retention-days: 1

      - name: Publish to GitHub Package
        if: needs.context.outputs.isRelease == 'true' && env.ENABLE_GH_MAVEN == 'true'
        run: |
          args=( -Pversion=${{ needs.context.outputs.version }} \
                 -PsemanticVersion=${{ needs.context.outputs.semanticVersion }} \
                 -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                 -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                 -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                 -Pnexus.username=${{ github.repository_owner }} \
                 -Pnexus.password=${{ secrets.OSS_GITHUB_TOKEN }} )
          args+=( -Pgithub )
          [[ "${{ needs.context.outputs.isRelease }}" == 'true' ]] && args+=( -Prelease )
          ./gradlew publish "${args[@]}"

      - name: Publish to Sonatype OSSRH
        if: needs.context.outputs.shouldPublish == 'true'
        run: |
          args=( -Pversion=${{ needs.context.outputs.version }} \
                 -PsemanticVersion=${{ needs.context.outputs.semanticVersion }} \
                 -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                 -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                 -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                 -Pnexus.username=${{ secrets.OSS_SONATYPE_USER }} \
                 -Pnexus.password=${{ secrets.OSS_SONATYPE_PASSWORD }} )
          [[ "${{ needs.context.outputs.isRelease }}" == 'true' ]] && args+=( -Prelease )
          ./gradlew publish "${args[@]}"

  analysis:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-test

      - name: Test
        run: ./gradlew jacocoRootReport -PjacocoHtml=false

      - name: SonarQube
        if: always() && needs.context.outputs.shouldPublish == 'true'
        run: ./gradlew sonarqube -x test -Dsonar.login=${{ secrets.OSS_SONARQUBE_TOKEN }} -Dsonar.branch.name=${{ needs.context.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [ build, context ]
    if: needs.context.outputs.isRelease == 'true'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: iot
          path: ./
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.context.outputs.branch }}
          name: Release ${{ needs.context.outputs.branch }}
          draft: false
          prerelease: false
          files: |
            ./*.zip

  promote:
    name: Promote Sonatype OSSRH
    runs-on: ubuntu-latest
    needs: [ build, context ]
    if: needs.context.outputs.isRelease == 'true'
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./gradlew closeAndReleaseRepository \
                            -Pnexus.username=${{ secrets.OSS_SONATYPE_USER }} \
                            -Pnexus.password=${{ secrets.OSS_SONATYPE_PASSWORD }} || echo 'Need to promote manually'
